version: '3.5'

services:
  app-node:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image:  mongo:4.4.4
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test
  
  mongo-express:
    image:  mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_AUTH_USERNAME: test
      ME_CONFIG_MONGODB_AUTH_USERNAME: test
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
    depends_on:
      - db
